name: cooknow
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.1.4
  pinput: ^5.0.0
  carousel_slider: ^4.2.1
  animated_bottom_navigation_bar: ^1.3.3
  tab_container: ^3.5.3
  image_picker: ^1.1.2
  video_player: ^2.8.7
  graphql: ^5.2.0-beta.8
  graphql_flutter: ^5.2.0-beta.7
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.2
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - .env
