// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr4Jwpf_1sF1Rvx-FExqzQYr_rosiIzmo',
    appId: '1:538874086903:web:1b12640a13eb486c0e1af2',
    messagingSenderId: '538874086903',
    projectId: 'cooknow-b55d0',
    authDomain: 'cooknow-b55d0.firebaseapp.com',
    storageBucket: 'cooknow-b55d0.appspot.com',
    measurementId: 'G-WMTR7QNTHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCst3rM84D0HSpr84IyhNNqSNRpPxcXNvQ',
    appId: '1:538874086903:android:94c41592c29503990e1af2',
    messagingSenderId: '538874086903',
    projectId: 'cooknow-b55d0',
    storageBucket: 'cooknow-b55d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0XRhez95XYkMQYPolUc0_3QQv6nTjr1k',
    appId: '1:538874086903:ios:bc56eb25254118b30e1af2',
    messagingSenderId: '538874086903',
    projectId: 'cooknow-b55d0',
    storageBucket: 'cooknow-b55d0.appspot.com',
    iosClientId: '538874086903-gpjttk6tmnd1p9gvbelm5ae9jlrcp46b.apps.googleusercontent.com',
    iosBundleId: 'com.example.cooknow',
  );

}